- .github/workflows/build.yml
I changed the CI runner from macOS to Linux because Linux runners are basically cheaper than macOS runners.
> ci: Change runner from macOS to Linux

- .github/workflows/build.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-06-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-06-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-26-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-26-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-27-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-27-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-29-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-29-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-02-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-02-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-24-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-24-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-25-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-25-a

- .github/workflows/build.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-5.10-SNAPSHOT-2024-05-30-a
> ci: bump Swift SDK to swift-wasm-5.10-SNAPSHOT-2024-05-30-a

- .github/workflows/build.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-5.10-SNAPSHOT-2024-06-01-a
> ci: bump Swift SDK to swift-wasm-5.10-SNAPSHOT-2024-06-01-a

- .github/workflows/build.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-5.10.0-RELEASE
> ci: bump Swift SDK to swift-wasm-5.10.0-RELEASE

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-06-04-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-06-04-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-05-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-05-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-07-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-07-a

- Sources/swift-format/Frontend/FormatFrontend.swift
> fix: make `format -i` to work again

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-06-08-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-06-08-a

- Sources/swift-format/Frontend/FormatFrontend.swift
cherry-picks 1e0635d3eb0aa4a813ffe765ea2dd10805a271bf to wasm32-wasi-release/6.0
> Cherry-pick "fix: make `format -i` to work again" to 6.0

- Sources/swift-format/Frontend/FormatFrontend.swift
cherry-picks 1e0635d3eb0aa4a813ffe765ea2dd10805a271bf to wasm32-wasi-release/5.10
> Cherry-pick "fix: make `format -i` to work again" to 5.10

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-08-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-08-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-06-09-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-06-09-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-09-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-09-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-14-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-14-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-06-14-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-06-14-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-06-23-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-06-23-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-07-05-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-07-05-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-07-08-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-07-08-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-07-10-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-07-10-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-07-16-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-07-16-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-07-16-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-07-16-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-07-20-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-07-20-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-08-30-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-08-30-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-08-30-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-08-30-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-07-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-07-a

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-09-18-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-09-18-a

- .github/workflows/Swift.yml
I've used the latest wasmtime in the CI, but that sometimes broke the CI, so I'm going to pin its version.
> ci: pin wasmtime version to 24.0.0

- .github/workflows/Swift.yml
- https://github.com/bytecodealliance/wasmtime/releases/tag/v25.0.0
- https://github.com/bytecodealliance/wasmtime/releases/tag/v25.0.1
> ci: bump wasmtime to 25.0.1

- .github/workflows/Swift.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-26-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-26-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v25.0.2
> ci: bump wasmtime to 25.0.2

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-10-10-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-10-10-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-15-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-15-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0-SNAPSHOT-2024-10-16-a
> ci: bump Swift SDK to swift-wasm-6.0-SNAPSHOT-2024-10-16-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v26.0.0
> ci: bump wasmtime to 26.0.0

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-27-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-27-a

- .github/pull.yml
resolves #119
[pull](https://github.com/wei/pull) is a GitHub App that keeps forks up-to-date with upstream via automated pull requests.
> chore: introduce pull

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0.2-RELEASE
> ci: bump Swift SDK to swift-wasm-6.0.2-RELEASE

- .github/workflows/swiftwasm.yml
- Package.swift
- Sources/swift-format/PrintVersion.swift
- Merge [600.0.0](https://github.com/swiftlang/swift-format/commits/600.0.0/) into wasm32-wasi-release/6.0.0
- bump Swift SDK to swift-wasm-6.0.2-RELEASE
- bump wasmtime to 26.0.0
> Release 600.0.0

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-S NAPSHOT-2024-10-31-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-31-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v26.0.1
> ci: bump wasmtime to 26.0.1

- .github/workflows/swiftwasm.yml
I cherry-picked #140 to wasm32-wasi-release/6.0 for the future release of 6.0.x.
> ci: remove `-all` from `wasm-opt` and add a job to test swift-format.wasm

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-15-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-15-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v27.0.0
> ci: bump wasmtime to 27.0.0

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-20-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-20-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-21-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-21-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-24-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-24-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-29-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-29-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-30-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-30-a

- .github/workflows/pull_request.yml
- Sources/SwiftFormat/API/Configuration.swift
- Sources/SwiftFormat/CMakeLists.txt
- Sources/SwiftFormat/Utilities/FileIterator.swift
- Sources/SwiftFormat/Utilities/URL+isRoot.swift
- Tests/SwiftFormatTests/Utilities/FileIteratorTests.swift
- api-breakages.txt
- **Fix support for `FileIterator` when working directory is `/`**
- **Add an api-breakages file to allow API breakages**
> Merge main into wasm32-wasi

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-05-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-05-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-17-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-17-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2024-12-17-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2024-12-17-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-20-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-20-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2024-12-21-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2024-12-21-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v28.0.0
> ci: bump wasmtime to 28.0.0

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-23-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-23-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-04-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-04-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-06-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-06-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-11-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-11-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v28.0.1
> ci: bump wasmtime to 28.0.1

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-15-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-15-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-17-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-17-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v29.0.0
> ci: bump wasmtime to 29.0.0

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-11-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-11-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v29.0.1
> ci: bump wasmtime to 29.0.1

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-23-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-23-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-24-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-24-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-25-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-25-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-26-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-26-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-01-30-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-01-30-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-02-07-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-02-07-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-02-10-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-02-10-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-02-14-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-02-14-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-02-18-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-02-18-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-02-19-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-02-19-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-02-21-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-02-21-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-03-04-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-03-04-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-04-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-04-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-03-06-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-03-06-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-03-07-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-03-07-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-10-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-10-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-03-12-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-03-12-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-14-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-14-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-17-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-17-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v31.0.0
> ci: bump wasmtime to 31.0.0

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-03-20-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-03-20-a

- Tests/SwiftFormatTests/Utilities/FileIteratorTests.swift
If swiftlang/swift-foundation#992 is merged, this workaround will no longer be needed.
> test(wasi): remove a workaround for `FileManager.createFile()`

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.0.3-RELEASE
> ci: bump Swift SDK to swift-wasm-6.0.3-RELEASE

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-SNAPSHOT-2025-04-05-a
> ci: bump Swift SDK to swift-wasm-6.1-SNAPSHOT-2025-04-05-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-6.1-RELEASE
> ci: bump Swift SDK to swift-wasm-6.1-RELEASE

- .github/workflows/swiftwasm.yml
- README.md
I added `swift-format-threads.wasm` to the artifacts, and changed the test jobs to also run on `wasm32-unknown-wasip1-threads`.
> Add wasm32-wasip1-threads artifact and tests

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-04-03-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-04-03-a

- .github/workflows/swiftwasm.yml
- README.md
- #55 
- #326 
- This toolchain was created just in time before the release/6.2 branches were cut from the main branches.
> Cherry-pick #55 and #326 to wasm32-wasi-release/6.2

- .github/workflows/swiftwasm.yml
- README.md
I added `swift-format-threads.wasm` to the artifacts, and changed the test jobs to also run on `wasm32-unknown-wasip1-threads`.
> ci: add wasm32-wasip1-threads artifact and tests

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-04-12-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-04-12-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-11-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-11-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-12-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-12-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-14-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-14-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-29-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-29-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-06-12-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-06-12-a

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-06-17-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-06-17-a

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v34.0.0
> ci: bump wasmtime to 34.0.0

- .github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-06-22-a
> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-06-22-a

- Package.swift
apple/swift-argument-parser has been broken for wasm32-unknown-wasi since 1.6.0, so I'm replacing it with my patched branch temporarily.
> fix: fix ArgumentParser build failure for WASI

- Package.swift
swift-argument-parser has been fixed, so I'm partially reverting #412.
> revert: partially revert "replace apple/swift-argument-parser with kkebo/swift-argument-parser"

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v34.0.2
> ci: bump wasmtime to 34.0.2

- .github/workflows/swiftwasm.yml
- Scripts/ci-install-swiftly.sh
Pros:
- We can use the latest nightly toolchain as soon as possible.
- We no longer need to worry about the gzip issue.
Cons:
- CI execution time is a little bit longer.
> ci: use swiftly instead of swiftlang/swift images

- .github/workflows/swiftwasm.yml
Swift SDK for Wasm is now published on swift.org, but it doesn't seem to have an SDK for wasm32-wasip1-threads.
> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-07-23-a_wasm

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/955e1e534160abb555a694a0113e981ad08f4312
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-25-a_wasm

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/2cb98582efc366cc608149bc9ff5f96154c82933
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-26-a_wasm

- Package.swift
Now, [swiftlang/swift-markdown](https://github.com/swiftlang/swift-markdown) and [swiftlang/swift-cmark](https://github.com/swiftlang/swift-cmark) support Wasm on their main branches, so let's use them.
> build: use swiftlang/swift-markdown

- .github/workflows/swiftwasm.yml
WasmKit is now included in the Swift toolchain, so it's easy to use.
However, since it doesn’t support `readlink()` yet, I’ll keep the `test` job unchanged.
https://github.com/kkebo/swift-format/pull/97#issuecomment-2400315855
> ci: use wasmkit instead of wasmtime on `test-binary`

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/5dabd85c27190c7fb446c121f2189eb4a4f29186
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-08-06-a_wasm

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/4401243a4fa7d1b3cc2cef03511b5ccec6960e63
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-08-19-a_wasm

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v36.0.0
> ci: bump wasmtime to 36.0.0

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v36.0.1
> ci: bump wasmtime to 36.0.1

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v36.0.2
> ci: bump wasmtime to 36.0.2

- .github/workflows/swiftwasm.yml
This workaround no longer seems to be needed.
> ci: remove a workaround for the gpg error due to gzip compression

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/d8416c6536a13e7cf0551c26f8096a00283c0a77
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-09-06-a_wasm

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v37.0.0
> ci: bump wasmtime to 37.0.0

- .github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v37.0.1
> ci: bump wasmtime to 37.0.1

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/edc5c2390a0669e095b0475376ad564989985dba
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-09-24-a_wasm

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/34a60a69b5b3807c5c51b46c69aec5421106d8a7
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-09-26-a_wasm

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/1dd5846759602bba27ab70da32f2a97f57ea0f1b
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-09-29-a_wasm

- .github/workflows/swiftwasm.yml
This is a defense against supply chain attacks. Moreover, GitHub [recommends SHA
pinning](https://github.blog/changelog/2025-08-15-github-actions-policy-now-supports-blocking-and-sha-pinning-actions/) these days.
> ci: pin GitHub Actions dependencies to commit SHA

- .github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/29bbbcd6ddc83da4ca87ab315f36a86848021475
> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-10-01-a_wasm
