Package.swift, Sources/SwiftFormat/Core/DocumentationComment.swift, Sources/SwiftFormat/Core/Pipelines+Generated.swift, Sources/SwiftFormat/Rules/BeginDocumentationCommentWithOneLineSummary.swift, Sources/SwiftFormat/Rules/ValidateDocumentationComments.swift
=> Enable swift-markdown again (#8)

Sources/_SwiftFormatInstructionCounter/include/InstructionsExecuted.h, Sources/swift-format/Subcommands/PerformanceMeasurement.swift
References
- https://forums.swift.org/t/webassembly-swiftpm/34343/7
=> revert: restore _SwiftFormatInstructionCounter

.github/workflows/build.yml
The current stack size is too large, so I'd like to shrink it as small as possible.
=> ci: reduce stack size

.github/workflows/Swift.yml, Package.swift
=> ci: add unit tests (#23)

Sources/SwiftFormat/PrettyPrint/Comment.swift, Sources/SwiftFormat/PrettyPrint/TokenStreamCreator.swift, Tests/SwiftFormatTests/PrettyPrint/CommentTests.swift
- **Merge adjacent .line and .docLine comments into a single element.**
- **Improvements based on feedback and further testing.**
=> Merge upstream/main into wasm32-wasi

.github/workflows/Swift.yml
I changed Swift.yml to reduce the number of environment variables as much as possible.
=> ci: refactor Swift.yml

.github/pull.yml
=> chore: fix branch name in pull.yml

.github/workflows/swiftwasm.yml
noble has a problem and I need time to fix it, so I've decided to downgrade to jammy.
=> ci: downgrade from noble to jammy

.github/workflows/swiftwasm.yml
=> ci: remove `-all` from `wasm-opt` and add a job to test swift-format.wasm

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v30.0.0
=> ci: bump wasmtime to 30.0.0

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v30.0.1
=> ci: bump wasmtime to 30.0.1

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v30.0.2
=> ci: bump wasmtime to 30.0.2

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v31.0.0
=> ci: bump wasmtime to 31.0.0

Package.swift, Sources/swift-format/PrintVersion.swift
=> Release 601.0.0

.github/pull.yml
=> chore: add release/6.2 to pull.yml

.github/pull.yml
Announcement: https://forums.swift.org/t/development-open-for-swift-6-1-1-for-linux-and-windows/79152
=> chore: add release/6.1.1 to pull.yml

.github/workflows/swiftwasm.yml
https://github.com/orgs/community/discussions/148648
=> ci: use GitHub-hosted arm64 Linux runners

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v32.0.0
=> ci: bump wasmtime to 32.0.0

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v33.0.0
=> ci: bump wasmtime to 33.0.0

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v34.0.1
=> ci: bump wasmtime to 34.0.1

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v34.0.2
=> ci: bump wasmtime to 34.0.2

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v35.0.0
=> ci: bump wasmtime to 35.0.0

.github/workflows/swiftwasm.yml
=> ci: fix SDK IDs (#433)

.github/workflows/swiftwasm.yml
context: https://github.com/orgs/community/discussions/26822
=> ci: add `results` job for required status checks

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/007569c2081d52b157ebaffb36a9ccffbda744be
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-07-24-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/c0c57bffc5233cc623d91467a3ca33ce2a4e6671
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-07-26-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/2167a1b6c1080346ee18cce46c721560f0f4412f
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-07-28-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/902fe4f6d0e2e05da4d1aaeb6b05a572bc6bb498
=> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-30-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/6ec8486c320569f1a2f473f888545260bba796ab
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-02-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/7d69b826cbd0c0e2448695f317f10191a79e3347
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-05-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/c2e971ad10924400850d91f1b22f6953b399f563
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-07-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/2d8aaf9f936622b27069537258f8f9e72a0583dd
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-08-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/b69b75e843c3bb210cdfabed67641fd7adacf0aa
=> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-08-10-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/c087bbac9c2d3ddd37dd88eb6359fb96f1ef055e
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-11-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/3dc98761d155070f05be1ea6e8c54bfd0b9d33a5
=> ci: bump Swift SDK to swift-6.2-DEVELOPMENT-SNAPSHOT-2025-08-14-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/e31c5bf573d984ad98342e82033875071dab9473
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-16-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/48526f9ad82bf375fc436d944fab0cab6ad0166d
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-18-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/1e9e927abf16ca947e9e1890fe9d444765773879
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-25-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/dbceabea508830103cecb0a6b275e6ee36acd9a4
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-27-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/c9bafa900c3c4c865291bf94881ceab9813c770b
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-09-13-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/2274f79a8ceb1142c043cfdc4c88a6c474bfeb9b
=> ci: bump Swift SDK to 6.2.0

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/3c962141480541055c8a920c2dc7f0ab4ff79587
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-09-19-a_wasm

.github/workflows/swiftwasm.yml
https://github.com/swiftlang/swift-org-website/commit/32e3abc44dac93fa7ca769bb823a53370011e1da
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-10-02-a_wasm

Scripts/ci-install-swiftly.sh
See https://www.shellcheck.net/wiki/SC1090.
=> ci: refactor shellcheck comment

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v37.0.2
=> ci: bump wasmtime to 37.0.2
